title: Guillermo Kulemeyer
description: >
  PhD Candidate · Machine Learning · Bioinformatics · PyTorch  
  Research Institute for Signals, Systems and Computational Intelligence (sinc(i), UNL–CONICET)

theme: jekyll-theme-cayman
show_downloads: false

